sudo: required
services:
  - docker

before_install:
  - docker build -t asm08/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true asm08/react-test npm test

after_success:
  - docker build -t asm08/multi-client ./client
  - docker build -t asm08/multi-server ./server
  - docker build -t asm08/multi-nginx ./nginx
  - docker build -t asm08/multi-worker ./worker
