sudo: required
services:
  - docker

before_install:
  - docker build -t asm08/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true asm08/react-test npm test

after_success:
  - docker build -t asm08/multi-client ./client
  - docker build -t asm08/multi-server ./server
  - docker build -t asm08/multi-nginx ./nginx
  - docker build -t asm08/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push asm08/multi-client
  - docker push asm08/multi-nginx
  - docker push asm08/multi-server
  - docker push asm08/multi-worker
