sudo: required
services:
  - docker

before_install:
  - docker build -t asm08/react-test -f ./client/Dockerfile.dev .

script: 
  - docker run asm08/react-test npm test -- --coverage

after_success:
  - docker build -t asm08/multi-client ./client
  - docker build -t asm08/multi-server ./server
  - docker build -t asm08/multi-nginx ./nginx
  - docker build -t asm08/multi-worker ./worker

script:
  - docker run -e CI=true USERNAME/react-test npm test